account/urls.py
from django.urls import path
from django.urls.conf import include
from account import views

app_name = "account"

urlpatterns = [
    # path('', include('django.contrib.auth.urls')),
    path('signup/', views.signup, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout")
]

aggregrator/urls.py
from django.urls import path
from aggregrator.views import scrape_view, news_list

app_name = "aggregrator"

urlpatterns = [  
#   path('scrape/', scrape_result, name="scrape"),  
  path('', scrape_view, name="search"),
  path('result/<int:id>', news_list, name="result")

]

aggrenews_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("aggregrator.urls")),
    path('account/', include("account.urls")),
]

account/models.py
from django.db import models

# Create your models here.

aggregrator/models.py
from django.db import models
from django.contrib.auth.models import User 

# Create your models here.
class Headline(models.Model):
  title = models.CharField(max_length=200)
  media_name = models.TextField(blank=True)
  date = models.DateField(null=True)
  image = models.URLField(null=True, blank=True)
  link = models.TextField()
  bodytext = models.TextField(blank=True)  
  requestor = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

class Search(models.Model):
    search_indonesian = models.TextField(max_length=20)
    search_english = models.TextField(max_length=20)

aggregrator/forms.py
from django import forms
from .models import Search

class SearchForm(forms.ModelForm):
    class Meta:
        model = Search
        fields = [
            'search_indonesian',
            'search_english',            
        ]

        widgets = {
            'search_indonesian': forms.TextInput(attrs= { 'class': 'form-control'} ),
            'search_english': forms.TextInput(attrs= { 'class': 'form-control'} )
        }

account/views.py
from django.http.response import HttpResponse, HttpResponseBadRequest, HttpResponseNotAllowed
from django.shortcuts import redirect, render
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup(request):
    if request.method == 'GET':
        form = UserCreationForm()
        context = {
            "form": form
        }
        return render(request, "registration/signup.html", context)
    elif request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(to="aggregrator:search")
        return HttpResponseBadRequest("Inputs are not valid")
    else:
        return HttpResponseNotAllowed()

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST) #request.POST is not the first expected parameter
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if ('next' in request.POST):
                return redirect(request.POST.get('next'))
            return redirect(to="aggregrator:search")        
    else: 
        form = AuthenticationForm()
    return render(request, 'registration/login.html', {'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect(to="account:login")

aggregrator/views.py
from django.shortcuts import redirect, render
from .scraper.Scrape import Scrape
from .build_wordcloud.build_wc import Build_WC
from .models import Headline, Search
from datetime import datetime
from .forms import SearchForm
from django.contrib.auth.decorators import login_required
from dotenv import load_dotenv
import os
load_dotenv(os.path.join(os.path.dirname(__file__), '..', 'aggrenews_project', '.env'))

# Create your views here.

@login_required(login_url="account/login/")
def scrape_view(request):

    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = SearchForm(request.POST)
        # check whether it's valid
        if form.is_valid():
            wc_text = []
            search_indonesian = form.cleaned_data['search_indonesian']
            search_english = form.cleaned_data['search_english']
            result = Scrape.scrape(search_indonesian)
            Headline.objects.filter(requestor=request.user.id).delete()
            print(request.user.username)
            for media in result.keys():
                for index, article_title in enumerate(result[media]['title']):            
                            
                    if (result[media]['date'][index] != ""):                        
                        date_time_obj = datetime.strptime(result[media]['date'][index], '%Y-%m-%d')
                    else:                        
                        date_time_obj = datetime.strptime('1970-01-01', '%Y-%m-%d')
                    
                    Headline.objects.create(
                        title = article_title,
                        media_name = result[media]['name'][index],
                        date = date_time_obj,
                        image = result[media]['imgSrc'][index],
                        link = result[media]['link'][index],
                        bodytext = result[media]['body'][index],     
                        requestor = request.user                   
                    )
                         
            return redirect('/result/' + str(request.user.id))

    elif request.method == 'GET':
        print('here is called')
        form = SearchForm()
        return render(request, 'home/home.html', {'form': form})

def news_list(request, id):
    headlines = Headline.objects.filter(requestor=id).order_by('-date')
    cloudinary_params = {
        'CLOUDINARY_NAME': os.getenv('CLOUDINARY_NAME'),
        'CLOUDINARY_API_KEY':  os.getenv('CLOUDINARY_API_KEY'),
        'CLOUDINARY_API_SECRET':  os.getenv('CLOUDINARY_API_SECRET')
    }
    
    wc_text = []
    for headline in headlines:
        wc_text.append(headline.bodytext)
    result_url = Build_WC.build_wc(wc_text, cloudinary_params)       
    context = {
        'object_list': headlines,
        'url': result_url
    }
    return render(request, 'result/result.html', context)

templates/base.html
<!DOCTYPE html>
<html>
<head>    
    <title>News Aggregrator</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    {% include 'navbar.html' %}

    {% block content %}

    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/home/home.html
{% extends '../base.html' %}
{% load static %}
{% block content %}

<div class='container mt-3'>
    <h1>News Scraper</h1>
    <p>Key in your keyword in Bahasa Indonesia and English (for Jakarta Post)</p>

    <form action="/" method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}  
        <div class='form-group mb-2'>
            {{ form.search_indonesian.errors }}
            <label for="{{ form.search_indonesian.id_for_label }}">Search (Indonesian):</label>
            {{ form.search_indonesian }}
        </div>
    
        <div class='form-group mb-2'>
            {{ form.search_english.errors }}
            <label for="{{ form.search_english.id_for_label }}">Search (English):</label>
            {{ form.search_english }}
        </div>
        
        <button id="submitBtn" class="btn btn-primary" type="submit" value="Submit">Submit</button>
        
        
    </form>

    <div id="message" class="mt-2 mb-2 d-none">You can either wait or go to {{ request.scheme }}://{{ request.get_host }}/result/{{ request.user.id }} in about 5 minutes.</div>
    <div id="progressBar" class="progress d-none" style="height: 20px;">
        <div class="progress-bar d-none" role="progressbar" style="width: 1%;"></div>
    </div>
    
</div>
<script src="{% static 'scrape.js' %}" type="text/javascript"></script>

{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/" style="margin-left: 2rem">Online Scraper</a>
    <button class="navbar-toggler" style="margin-right: 2rem" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup" >
        <div class="navbar-nav" style="margin-left: 2rem">  
            {% if user.is_authenticated %}                
            <form class="nav-item nav-link" action="{% url 'account:logout' %}" method='POST'>
                {% csrf_token %}
                <button class="btn btn-secondary" type='submit'>Logout</button>
            </form>
            {% else %}
            <a class="nav-item nav-link" href="{% url 'account:login' %}">Login</a>
            <a class="nav-item nav-link" href="{% url 'account:signup' %}">Register</a>            
            {% endif %}
        </div>
    </div>
</nav>

templates/result/result.html
{% extends '../base.html' %}
{% load static %}
{% block content %}
  <div class="container mt-3">
    <h1>Search Results</h1>
    <div class="row border pt-2 pb-2">
      <h3 class="mb-2">Word Cloud</h3>
      <img src="{{ url }}" alt="wordcloudimg" style="width: 70%; margin: 0 auto;"/>
    </div>
  {% for object in object_list %}
    <div class="row border pt-2 pb-2">
      <div class="col-md-2 pt-2">
        <img src="{{ object.image }}" alt="image" style="width: 100%"/>
      </div>
      <div class="col-md-10">
        <p>{{ object.date }}</p>
        <p class='text-success'>{{ object.media_name }}</p>
        <a href="{{ object.link }}"><h5>{{ object.title }}</h5></a>        
        <p class="text-truncate">{{ object.bodytext }}</p>
        <span class="readmore text-info" style="cursor: pointer">Read More</span>
      </div>
    </div>  
  {% endfor %}
</div>
  <script src="{% static 'home.js' %}" type="text/javascript"></script>
{% endblock %}